import { TwitterApi, TwitterApiReadWrite } from "twitter-api-v2";
import { Match, MatchPlayer, TwitchUsername } from "../types";
import Config from "../utils/config";
import logger from "../utils/logger";

export type MatchTweetData = {
  match: Match;
  author: TwitchUsername;
};

export default class TwitterService {
  private static readonly BOT_USERNAME = "whysoryude";
  private static twitterClient: TwitterApiReadWrite;

  public static init() {
    this.twitterClient = new TwitterApi({
      appKey: Config.TWITTER_API_KEY,
      appSecret: Config.TWITTER_API_KEY_SECRET,
      accessToken: Config.TWITTER_ACCESS_TOKEN,
      accessSecret: Config.TWITTER_ACCESS_TOKEN_SECRET,
    }).readWrite;

    logger.info("connected to twitter");
  }

  public static tweetMatch(matchData: MatchTweetData): Promise<void> {
    const tweetText = this.buildMatchTweetText(matchData);

    return this.twitterClient.v2
      .tweet(tweetText)
      .then(() => {
        logger.info("tweet successfully created", { tweetText });
      })
      .catch((err) => {
        logger.error("something went wrong", err);
      });
  }

  public static async isMatchTweeted(
    matchData: MatchTweetData
  ): Promise<boolean> {
    const searchText = this.buildMatchTweetText(matchData, false);
    const result = await this.twitterClient.v2.search(
      `"${searchText}" (from:${this.BOT_USERNAME})`
    ); // twitter throws error on duplicate content too "You are not allowed to create a Tweet with duplicate content."

    return result.data.meta.result_count > 0;
  }

  private static buildMatchTweetText(
    matchData: MatchTweetData,
    includeLinks: boolean = true // we need this because search doesn't work with urls
  ): string {
    const { blueTeam, redTeam } = matchData.match;
    let text = "";

    text += `TOP 🏔 ${this.buildPlayerText(blueTeam[0], includeLinks)}\n`;
    text += `JGL 🌲 ${this.buildPlayerText(blueTeam[1], includeLinks)}\n`;
    text += `MID 🪄 ${this.buildPlayerText(blueTeam[2], includeLinks)}\n`;
    text += `BOT 🏹 ${this.buildPlayerText(blueTeam[3], includeLinks)}\n`;
    text += `SUP 🛡 ${this.buildPlayerText(blueTeam[4], includeLinks)}\n\n`;

    text += "vs\n\n";

    text += `TOP 🏔 ${this.buildPlayerText(redTeam[0], includeLinks)}\n`;
    text += `JGL 🌲 ${this.buildPlayerText(redTeam[1], includeLinks)}\n`;
    text += `MID 🪄 ${this.buildPlayerText(redTeam[2], includeLinks)}\n`;
    text += `BOT 🏹 ${this.buildPlayerText(redTeam[3], includeLinks)}\n`;
    text += `SUP 🛡 ${this.buildPlayerText(redTeam[4], includeLinks)}`;

    if (includeLinks) {
      text += `\n\n`;
      text += `Generated by: ${matchData.author} (https://www.twitch.tv/${matchData.author})`;
    }

    return text;
  }

  private static buildPlayerText(
    matchPlayer: MatchPlayer,
    includeLinks: boolean = true
  ): string {
    let text = matchPlayer.summonerNameWithTeam;

    if (matchPlayer.isStreaming && includeLinks) {
      text += ` (https://www.twitch.tv/${matchPlayer.twitchUsername})`;
    }

    return text;
  }
}
